Repository InseeFrLab/utilitR, pull requests merged in 2021-06, with the labels that each got.

#354 Remove warning readr
  03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd
Labels: bug, rendering

#359 Inversion d'un ~ et d'un ==
  03_Fiches_thematiques/Fiche_datatable.Rmd
Labels: bug, relecture

#365 Typo - fiche données spatiales
  03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
Labels: relecture

#370 Typo - ggplot2
  03_Fiches_thematiques/Fiche_graphiques.Rmd
Labels: relecture

#372 Ajout conseil sur zonage à façon
  03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
Labels: contributions, fiches thématiques

#373 Flou artistique
  01_R_Insee/Fiche_utiliser_ressources.Rmd
  pics/utiliser_ressources/TskMngr2.png
  pics/utiliser_ressources/TskMngr2bis.png
Labels: bug, relecture
